id: PYSEC-2018-23
package:
  name: pyopenssl
  ecosystem: PyPI
details: 'Python Cryptographic Authority pyopenssl version prior to version 17.5.0
  contains a CWE-416: Use After Free vulnerability in X509 object handling that can
  result in Use after free can lead to possible denial of service or remote code execution..
  This attack appear to be exploitable via Depends on the calling application and
  if it retains a reference to the memory.. This vulnerability appears to have been
  fixed in 17.5.0.'
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 17.5.0
references:
- type: WEB
  url: https://github.com/pyca/pyopenssl/pull/723
- type: WEB
  url: https://usn.ubuntu.com/3813-1/
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:0085
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html
aliases:
- CVE-2018-1000807
modified: "2019-09-27T12:21:00Z"
published: "2018-10-08T15:29:00Z"
