id: PYSEC-2018-24
package:
  name: pyopenssl
  ecosystem: PyPI
details: 'Python Cryptographic Authority pyopenssl version Before 17.5.0 contains
  a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability
  in PKCS #12 Store that can result in Denial of service if memory runs low or is
  exhausted. This attack appear to be exploitable via Depends upon calling application,
  however it could be as simple as initiating a TLS connection. Anything that would
  cause the calling application to reload certificates from a PKCS #12 store.. This
  vulnerability appears to have been fixed in 17.5.0.'
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 17.5.0
references:
- type: WEB
  url: https://github.com/pyca/pyopenssl/pull/723
- type: WEB
  url: https://usn.ubuntu.com/3813-1/
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:0085
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html
aliases:
- CVE-2018-1000808
modified: "2020-10-15T13:28:00Z"
published: "2018-10-08T15:29:00Z"
